apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: springpetclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: springpet_pod
      labels:
        app: springpetclinic
    spec: 
      containers:
        - name: springpetclinic
          image: danish84464/pipeline:latest
          ports:
            - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-service
spec:
  selector:
    app: springpetclinic
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80

  type: LoadBalancer
  externalIPs:
    - 54.65.255.25

