apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deploy
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: springpetclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: springpet_pod
      labels:
        app: springpetclinic
    spec: 
      containers:
        - name: springpetclinic
          image: danish84464/app:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-service
spec:
  selector:
    app: springpetclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
